// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(FavContext))]
    partial class FavContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("backend.Data.EmsFavs", b =>
                {
                    b.Property<int>("FavId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FavName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FavRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FavType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FavId");

                    b.ToTable("Favs");
                });
#pragma warning restore 612, 618
        }
    }
}
